services:
  tribute-workers:
    image: node:20-bookworm-slim
    working_dir: /app
    command:
      - /bin/sh
      - -lc
      - |
        corepack enable >/dev/null 2>&1 || true
        if [ ! -d node_modules ]; then
          pnpm install --frozen-lockfile
        fi
        /app/scripts/docker/dev-worker.sh infra/wrangler-dos.toml 8789 &
        /app/scripts/docker/dev-worker.sh infra/wrangler-api.toml 8788 &
        /app/scripts/docker/dev-worker.sh infra/wrangler.toml 8787 &
        wait
    environment:
      NODE_ENV: development
      TOKEN_SIGNING_KEY: dev-signing-key
      ENABLE_DEV_BOOTSTRAP: "true"
      EXAMPLE_ORIGIN_TOKEN: local-dev-secret
      ALLOWED_ORIGINS: "http://localhost:5173 http://127.0.0.1:5173"
      WRANGLER_TELEMETRY_DISABLE: "1"
    ports:
      - "8787:8787"
      - "8788:8788"
      - "8789:8789"
    volumes:
      - .:/app
      - wrangler_state:/app/.wrangler/state

  tribute-dashboard:
    image: node:20-bookworm-slim
    working_dir: /app
    command:
      - /bin/sh
      - -lc
      - |
        corepack enable >/dev/null 2>&1 || true
        if [ ! -d node_modules ]; then
          pnpm install --frozen-lockfile
        fi
        pnpm --filter dashboard dev
    environment:
      NODE_ENV: development
      VITE_TRIBUTE_ENABLE_AUTH: "false"
      VITE_TRIBUTE_ADMIN_USER_ID: admin-user
      VITE_TRIBUTE_DEFAULT_USER_ID: demo-user
    ports:
      - "5173:5173"
    volumes:
      - .:/app

  tribute-console:
    build:
      context: ./nginx
    environment:
      LISTEN_IPV6: "0"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro

  fastapi-origin:
    build:
      context: ./examples/origins/fastapi
    environment:
      TRIBUTE_API_KEY: local-dev-secret
      TRIBUTE_ROOT_PATH: /apps/fastapi
    ports:
      - "9100:9000"

  fastify-origin:
    build:
      context: ./examples/origins/fastify
    environment:
      TRIBUTE_API_KEY: local-dev-secret
    ports:
      - "3300:3000"

  tribute-bootstrap:
    image: curlimages/curl:8.11.1
    working_dir: /app
    entrypoint: ["/bin/sh", "/app/scripts/docker/bootstrap.sh"]
    depends_on:
      - tribute-workers
      - fastapi-origin
      - fastify-origin
    volumes:
      - .:/app

volumes:
  wrangler_state:
