name = "tribute-durable-objects"
main = "../dos/src/index.ts"
compatibility_date = "2024-03-25"

[vars]
ENVIRONMENT = "dev"

[durable_objects]
bindings = []

[[migrations]]
tag = "v1"
new_classes = ["RedeemDurableObject", "MerchantDurableObject", "UserWalletDurableObject", "HistoryDurableObject"]
