name = "tribute-edge-proxy"
main = "../edge-proxy/src/index.ts"
compatibility_date = "2024-03-25"
logpush = true

[vars]
ENVIRONMENT = "dev"
CACHE_MAX_KV_BYTES = 120000
CACHE_TTL_SECONDS = 604800
MANAGEMENT_ALLOWED_HOSTS = "localhost:8787 127.0.0.1:8787 localhost:5173 127.0.0.1:5173"
ALLOWED_ORIGINS = "http://localhost:5173 http://127.0.0.1:5173"

[[durable_objects.bindings]]
name = "REDEEM_DO"
class_name = "RedeemDurableObject"
script_name = "tribute-durable-objects"

[[durable_objects.bindings]]
name = "MERCHANT_DO"
class_name = "MerchantDurableObject"
script_name = "tribute-durable-objects"

[[durable_objects.bindings]]
name = "MERCHANT_APP_DO"
class_name = "MerchantAppDurableObject"
script_name = "tribute-durable-objects"

[[durable_objects.bindings]]
name = "USER_WALLET_DO"
class_name = "UserWalletDurableObject"
script_name = "tribute-durable-objects"

[[durable_objects.bindings]]
name = "HISTORY_DO"
class_name = "HistoryDurableObject"
script_name = "tribute-durable-objects"

[[kv_namespaces]]
binding = "RECEIPTS_KV"
id = "__REPLACE_WITH_RECEIPTS_NS__"
preview_id = "__LOCAL_RECEIPTS_NS__"

[[kv_namespaces]]
binding = "NONCES_KV"
id = "__REPLACE_WITH_NONCES_NS__"
preview_id = "__LOCAL_NONCES_NS__"

[[kv_namespaces]]
binding = "JWK_KV"
id = "__REPLACE_WITH_JWK_NS__"
preview_id = "__LOCAL_JWK_NS__"

[[r2_buckets]]
binding = "ARTIFACTS_R2"
bucket_name = "tribute-artifacts"
preview_bucket_name = "tribute-artifacts-dev"

[[r2_buckets]]
binding = "REPORTS_R2"
bucket_name = "tribute-reports"
preview_bucket_name = "tribute-reports-dev"

[[queues.producers]]
queue = "stripe-webhooks"
binding = "STRIPE_WEBHOOK_QUEUE"

[observability]
enabled = true

[placement]
mode = "smart"
